# Generated by Django 4.2.6 on 2023-10-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="Имя пользователя"),
                ),
                ("age", models.IntegerField(verbose_name="Возраст пользователя")),
            ],
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название задачи"),
                ),
                ("description", models.TextField()),
                (
                    "created_task",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания задачи"
                    ),
                ),
                (
                    "finished_task",
                    models.BooleanField(default=False, verbose_name="Задача окончена"),
                ),
                (
                    "priority",
                    models.BooleanField(default=False, verbose_name="Приоритет задачи"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Tasksapp.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Tasksapp.tasks"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Tasksapp.user"
                    ),
                ),
            ],
        ),
    ]
